### ISSUE TITLE
CS9057 The analyzer assembly references version problem

### ISSUE THREAD

**Issue by ChrisTorng** [linkdotnet/BuildInformation#11]
We are using VS 2022. I added this NuGet package without error.
But other people on the same sln has problem, and the build failed, no code generated:
```
Warning CS9057: The analyzer assembly 'C:\Users\xxx\.nuget\packages\linkdotnet.buildinformation\0.4.1\analyzers\dotnet\cs\LinkDotNet.BuildInformation.dll' references version '4.6.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'.
```
I add `Microsoft.Net.Compilers.Toolset 4.7.0` to solve this problem.
I don't think this is the best solution. Do you have any idea?

**Comment by linkdotnet** [comment]
Hey - yes adding `Microsoft.Net.Compilers.Toolset` might solve the issue but is not the best choice either. Especially because you are not depending on it at all.

Is VS 2022 up to date on the other machines? I changed the referenced package and will push a new version (0.4.2) soon - let me know if that helps.

**Comment by ChrisTorng** [comment]
I updated to 0.4.2, removed `Microsoft.Net.Compilers.Toolset`. The same problem reappear. But the referenced version changed from 4.6.0.0 to 4.7.0.0. (Currently is still 4.4.0.0).
I can ask others to upgrade their VS version, but the same problem happens in my CI environment. It's hard for me to upgrade the CI environment version.
I had other analyzers with source generator worked well. Like System.Text.Json.
We have .NET Core 7.0/.NET Framework 4.8.0 projects. Other people has issues on both projects. But only .NET Framework project has issue in CI. The CI uses msbuild on .NET Framework project, which is different from other .NET Core projects use dotnet build.

**Comment by linkdotnet** [comment]
The only change I did recently was to upgrade said package from `4.6.0` to `4.7.0`.
**In theory** that shouldn't have any impact due to the fact, that also `4.7.0` supports `netstandard2.0` and `net4.7` (see [NuGet](https://www.nuget.org/packages/Microsoft.CodeAnalysis#dependencies-body-tab)).

I guess you had no issues with the generator in version 0.4 - so as a quick fix, I could revert the package version to `4.6.0`.

Alternatively, there is a [thread on StackOverflow](https://stackoverflow.com/questions/76740942/how-to-fix-the-analyzer-assembly-references-version-4-7-0-0-of-the-compiler) discussing exactly that issue - it might be worth trying this out.

**Comment by ChrisTorng** [comment]
I ask others to upgrage VS 2022 to latest version (not preview), all problems solved.
For the .NET Framework project on CI, I tried reference `Microsoft.CodeAnalysis.CSharp` or `Microsoft.CodeAnalysis` 4.7.0 directly, but failed.
Currently I need to reference `Microsoft.Net.Compilers.Toolset` only for CI using MSBuild for .NET Framework project.

**Comment by linkdotnet** [comment]
Interesting - do you see this issue with any source generator?
If so, I would be very interested if they updated the package in question recently. I also assume that your CI has a different msbuild version than your local dev environment, leading to the problem.

**Comment by ChrisTorng** [comment]
The CI environment isn't maintained by me. While upgrading from .NET 6.0 to 7.0, we can't build the .NET Framework project. At last found that MSBuild can solve the problem. Now the build way of .NET Framework project is different from other .NET Core projects, we won't try other ways to solve problems. Currently I can accept the workaround of reference `Microsoft.Net.Compilers.Toolset`. If you wish to try other fixes from your project, I can still help. If not, it's ok to close this issue. Thanks for your kindly help.

**Comment by linkdotnet** [comment]
The only way to solve that for `net4.8` would be to roll back to an old version of the package. 
But from the given message above, it seems I would have to roll back even to an older version (`4.4.0`).
If it is no major inconvenience, I would keep it as it is. I am pretty certain that the current `msbuild` version should not lead to the issue.
Are there any plans for you to migrate to a newer .NET version in the near/middle future?

**Comment by ChrisTorng** [comment]
I'm planning to migrate the next year. Thanks for help, I'll close this issue.

**Comment by linkdotnet** [comment]
Thanks - let me know if I can help you somewhere else. Cheers

**Comment by ChrisTorng** [comment]
I met the same problem after upgrade to 2.1.3:

> Warning CS9057: Analyzer assembly '...\.nuget\packages\linkdotnet.buildinformation\2.1.4\analyzers\dotnet\cs\LinkDotNet.BuildInformation.dll' cannot be used because it references version '5.0.0.0' of the compiler, which is newer than the currently running version '4.14.0.0'.

It should be the change in https://github.com/linkdotnet/BuildInformation/commit/d05edc630e617aedb8e3a46ddb25b6ea39107392 : Bump Microsoft.CodeAnalysis.CSharp from 4.14.0 to 5.0.0

The same trick of installing `Microsoft.Net.Compilers.Toolset` 5.3.0 solved the problem.

Is the upgrade of `Microsoft.CodeAnalysis.CSharp` necessary? If not, may you downgrade it to make it support for broader projects?

**Comment by linkdotnet** [comment]
Yeah we can downgrade that for sure.

**Comment by linkdotnet** [comment]
New version will be out in a second: `2.1.5` that goes back to `4.14.0` for `Microsoft.CodeAnalysis.CSharp`

Thanks @ChrisTorng for the info
