### ISSUE TITLE
Get Custom Build Configuration?

### ISSUE THREAD

**Issue by arivoir** [linkdotnet/BuildInformation#8]
I see the compilation options give an enum Debug|Release for the build configuration, but I'm not seeing how to get the real configuration. 
Do you think it is possible to get the real build configuration when using a custom configuration?

**Comment by linkdotnet** [comment]
Hey @arivoir,

I had a quick check, and it is possible to get solution configuration so to speak.
My question to you is:

Did you expect `BuildInformation.Configuration` to have this value or would you expect an additional property to reflect that information.

**Comment by linkdotnet** [comment]
I will push a release `0.4.1` that will respect the solution configuration first - and when not given will fallback to project level.
It will be using the currently available `BuildInformation.Configuration` - Let me know if that fits your expectation.

**Comment by arivoir** [comment]
I think that’s ok. Thanks for the answer and changes!
